[package]
name = "ashell"
description = "Barely customizable Wayland status bar for Hyprland compositor."
homepage = "https://github.com/MalpenZibo/ashell"
version = "0.1.2"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["tokio", "wgpu", "advanced"] }
iced_runtime = { version = "0.13.1", features = ["multi-window"] }
iced_layershell = "=0.9.4-rc3"
chrono = "0.4"
hyprland = { git = "https://github.com/MalpenZibo/hyprland-rs" }
serde = "1.0"
sysinfo = "0.30"
tokio = { version = "1", features = ["full"] }
zbus = "4.2"
libpulse-binding = { version = "2.28", features = ["pa_v15"] }
inotify = "0.10"
log = { version = "0.4", features=["serde"] }
flexi_logger = "0.28"
serde_yaml = "0.9"
pipewire = "0.8"
wayland-client = "0.31.5"
wayland-protocols = { version = "0.32.3", features = ["client", "unstable"] }
itertools = "0.13"
hex_color = { version = "3.0", features = ["serde"] }
anyhow = "1"

